name: secrets

on:
  push:

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
    - name: print secret
      run: echo "The secret is ${{ secrets.MY_SECRETS }}"
    - name: add secret to .env file
        run: echo "MY_SECRETS=${{ secrets.MYSECRETS }}" >> .env
    - name: Count the amount of characters
        run: wc -c .env
